2021-09-22 23:48:43,992 WARNING [connectionpool.py(urlopen:781)] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E3D4197400>: Failed to establish a new connection: [WinError 10061] ����Ŀ�����������ܾ����޷����ӡ�')': /session/d623d016ef36c77a05464670d1ab129e
